(()=>{'use strict';
const header=document.querySelector('.site-header'),nav=document.querySelector('#main-nav'),menu=document.querySelector('.menu-toggle'),trigger=document.querySelector('.nav-trigger'),dropdown=document.querySelector('.dropdown');
const closeDropdown=()=>{if(dropdown){dropdown.hidden=true;trigger.setAttribute('aria-expanded','false')}};
const setMenu=open=>{nav.classList.toggle('is-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');if(!open)closeDropdown()};
menu?.addEventListener('click',()=>setMenu(menu.getAttribute('aria-expanded')!=='true'));
trigger?.addEventListener('click',()=>{const open=dropdown.hidden;dropdown.hidden=!open;trigger.setAttribute('aria-expanded',String(open))});
document.addEventListener('click',e=>{if(!e.target.closest('.nav-group'))closeDropdown();if(!e.target.closest('.site-header'))setMenu(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(dropdown&&!dropdown.hidden){closeDropdown();trigger.focus()}else if(nav.classList.contains('is-open')){setMenu(false);menu.focus()}}});
document.querySelector('.nav-group')?.addEventListener('focusout',e=>{if(!e.currentTarget.contains(e.relatedTarget))closeDropdown()});
matchMedia('(min-width:1101px)').addEventListener('change',()=>setMenu(false));
let scrollQueued=false;function shadow(){header?.classList.toggle('scrolled',scrollY>8);scrollQueued=false}window.addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(shadow)}},{passive:true});shadow();
const hero=document.querySelector('.home-hero'),motion=document.querySelector('.motion-toggle'),reduced=matchMedia('(prefers-reduced-motion:reduce)');let paused=false;
function syncMotion(){if(!hero)return;const off=reduced.matches||paused;hero.classList.toggle('motion-paused',off);motion.setAttribute('aria-pressed',String(off));motion.textContent=reduced.matches?'Motion reduced':paused?'Play motion ▷':'Pause motion Ⅱ';motion.disabled=reduced.matches}
motion?.addEventListener('click',()=>{paused=!paused;syncMotion()});reduced.addEventListener('change',syncMotion);syncMotion();
const deck=document.querySelector('.deck');if(deck){const cards=[...deck.querySelectorAll('.deck-card')],dots=[...document.querySelectorAll('[data-slide]')],counter=document.querySelector('.deck-counter');let current=0,startX=0,startY=0,dragging=false,suppress=false;
function layout(){const narrow=innerWidth<=760,step=narrow?270:Math.min(390,deck.clientWidth*.32);cards.forEach((card,i)=>{let offset=(i-current+cards.length)%cards.length;if(offset>2)offset-=cards.length;const distance=Math.abs(offset),scale=distance===0?1:distance===1?.91:.77;card.style.transform=`translateX(${offset*step}px) translateY(${distance*8}px) translateZ(${-distance*65}px) rotateY(${offset===0?-16:offset<0?28:-28}deg) scale(${scale})`;card.style.zIndex=String(5-distance);card.style.opacity=distance===2?'.35':'1';card.style.pointerEvents=distance===2?'none':'auto';card.tabIndex=distance===2?-1:0;card.setAttribute('aria-hidden',String(distance===2));});dots.forEach((d,i)=>d.setAttribute('aria-pressed',String(i===current)));counter.textContent=String(current+1).padStart(2,'0')+' / 05'}
const move=n=>{current=(n+cards.length)%cards.length;layout()};document.querySelector('.deck-prev').addEventListener('click',()=>move(current-1));document.querySelector('.deck-next').addEventListener('click',()=>move(current+1));dots.forEach((d,i)=>d.addEventListener('click',()=>move(i)));deck.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(current+(e.key==='ArrowRight'?1:-1))}});deck.addEventListener('pointerdown',e=>{if(e.button!==0)return;startX=e.clientX;startY=e.clientY;dragging=true;suppress=false});deck.addEventListener('pointermove',e=>{if(dragging&&Math.abs(e.clientX-startX)>12&&Math.abs(e.clientX-startX)>Math.abs(e.clientY-startY))suppress=true});window.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))move(current+(dx<0?1:-1));setTimeout(()=>{suppress=false},0)});deck.addEventListener('pointercancel',()=>{dragging=false;suppress=false});deck.addEventListener('click',e=>{if(suppress)e.preventDefault()},true);deck.addEventListener('dragstart',e=>e.preventDefault());window.addEventListener('resize',layout);layout();}
const search=document.querySelector('#job-search'),location=document.querySelector('#job-location');if(search){const rows=[...document.querySelectorAll('.job-row')];function filter(){const query=search.value.trim().toLowerCase(),where=location.value;let count=0;rows.forEach(row=>{const visible=(row.dataset.search||row.textContent).toLowerCase().includes(query)&&(!where||row.dataset.location===where);row.hidden=!visible;if(visible)count++});document.querySelector('#job-count').textContent=count+' '+(count===1?'opportunity':'opportunities');document.querySelector('#no-jobs').hidden=count!==0}search.addEventListener('input',filter);location.addEventListener('change',filter)}
const form=document.querySelector('#inquiry-form');form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const f=new FormData(form);const body=`Name: ${f.get('name')}\nCompany: ${f.get('company')}\nEmail: ${f.get('email')}\nTelephone: ${f.get('phone')}\n\n${f.get('message')}`;window.location.href='mailto:info@activealliancecorp.com?subject='+encodeURIComponent('Website inquiry — '+f.get('name'))+'&body='+encodeURIComponent(body);document.querySelector('#form-status').textContent='Your email app will open with a draft. Review and send it there, or use our online inquiry form.'});
})();
